from __future__ import annotations

from types import SimpleNamespace

from app.services.drafting import composer
from app.services.drafting.citations import build_citations_from_bundle
from app.services.drafting.composer import compose_draft, compose_subject
from app.services.drafting.tone import resolve_tone_band


def test_tone_band_mapping() -> None:
    assert resolve_tone_band(20)["tone_band"] == "cool_professional"
    assert resolve_tone_band(55)["tone_band"] == "warm_professional"
    assert resolve_tone_band(90)["tone_band"] == "friendly_personal"


def test_compose_draft_uses_llm_result_when_available(monkeypatch) -> None:
    bundle = {
        "contact": {"display_name": "Jamie"},
        "objective": "follow up",
        "recent_interactions": [],
        "graph_claim_snippets": [],
        "email_context_snippets": [],
    }
    tone = {"tone_band": "warm_professional"}
    monkeypatch.setattr(
        "app.services.drafting.composer._compose_openai_draft",
        lambda *_args, **_kwargs: "LLM draft body",
    )

    draft = compose_draft(bundle, tone)

    assert draft == "LLM draft body"


def test_compose_draft_falls_back_to_template(monkeypatch) -> None:
    bundle = {
        "contact": {"display_name": "Jamie"},
        "objective": "follow up",
        "recent_interactions": [{"subject": "Project kickoff"}],
        "graph_claim_snippets": ["Current company: Acme"],
        "email_context_snippets": ["Thanks for the update on milestones."],
    }
    tone = {"tone_band": "cool_professional"}
    monkeypatch.setattr(
        "app.services.drafting.composer._compose_openai_draft",
        lambda *_args, **_kwargs: None,
    )

    draft = compose_draft(bundle, tone)

    assert "Hello Jamie," in draft
    assert "I wanted to follow up." in draft


def test_openai_draft_uses_tone_band_specific_style(monkeypatch) -> None:
    captured: dict[str, str] = {}

    monkeypatch.setattr(
        composer,
        "get_settings",
        lambda: SimpleNamespace(llm_provider="openai", llm_model="gpt-4o-mini"),
    )
    monkeypatch.setenv("OPENAI_API_KEY", "test-key")

    def fake_style_loader(tone_band: str | None = None) -> str:
        captured["tone_band"] = tone_band or ""
        return "STYLE-FRIENDLY"

    monkeypatch.setattr(composer, "load_combined_writing_style_instructions", fake_style_loader)

    def fake_render_prompt(key: str, **variables: str) -> str:
        if key == "draft_email_system":
            captured["style"] = variables["writing_style_instructions"]
            return "SYSTEM-PROMPT"
        return "USER-PROMPT"

    monkeypatch.setattr(composer, "render_prompt", fake_render_prompt)

    class _FakeCompletions:
        @staticmethod
        def create(**_kwargs):
            return SimpleNamespace(
                choices=[SimpleNamespace(message=SimpleNamespace(content="Generated by LLM"))]
            )

    class _FakeChat:
        completions = _FakeCompletions()

    class _FakeOpenAI:
        def __init__(self, api_key: str):
            self.api_key = api_key
            self.chat = _FakeChat()

    monkeypatch.setattr("openai.OpenAI", _FakeOpenAI)

    bundle = {
        "contact": {"display_name": "Jamie"},
        "objective": "follow up",
        "recent_interactions": [{"subject": "Project kickoff"}],
        "graph_claim_snippets": [],
        "email_context_snippets": [],
    }
    tone = {"tone_band": "friendly_personal"}

    draft = composer._compose_openai_draft(bundle, tone)

    assert draft == "Generated by LLM"
    assert captured["tone_band"] == "friendly_personal"
    assert captured["style"] == "STYLE-FRIENDLY"


def test_compose_subject_uses_recent_subject() -> None:
    bundle = {
        "objective": "reconnect",
        "recent_interactions": [{"subject": "Q1 planning"}],
    }
    subject = compose_subject(bundle, {"tone_band": "cool_professional"})
    assert subject.startswith("Follow-up:")
    assert "Q1 planning" in subject


def test_build_citations_maps_paragraphs_to_supporting_chunks() -> None:
    bundle = {
        "relevant_chunks": [
            {
                "interaction_id": "i-1",
                "chunk_id": "c-1",
                "span_json": {"start": 0, "end": 40},
                "text": "pricing proposal and budget discussion for Q2 pilot",
            },
            {
                "interaction_id": "i-2",
                "chunk_id": "c-2",
                "span_json": {"start": 41, "end": 80},
                "text": "timeline confirmation and workshop date options",
            },
        ]
    }
    draft_text = (
        "Hi Alex,\n\n"
        "Following up on the pricing proposal and budget discussion for the Q2 pilot.\n\n"
        "Could we confirm a workshop date and timeline next week?\n\n"
        "Best,\n[Your Name]"
    )

    citations = build_citations_from_bundle(bundle, draft_text=draft_text)

    paragraph_ids = {item["paragraph"] for item in citations}
    assert 2 in paragraph_ids
    assert 3 in paragraph_ids
    assert 4 not in paragraph_ids  # closer should not get arbitrary citations
    assert any(item["chunk_id"] == "c-1" and item["paragraph"] == 2 for item in citations)
    assert any(item["chunk_id"] == "c-2" and item["paragraph"] == 3 for item in citations)
