from __future__ import annotations

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.api.v1.deps import get_db
from app.api.v1.schemas import (
    CaseContactsListResponse,
    CaseOpportunitiesListResponse,
    CasePromotionRequest,
    CasePromotionResponse,
)
from app.db.neo4j.queries import (
    list_case_contacts_v2,
    list_case_opportunities_v2,
    promote_case_contact_v2,
    promote_case_opportunity_v2,
)
from app.db.pg.models import ContactCache, Interaction

router = APIRouter(prefix="/cases", tags=["cases"])


@router.get("/contacts", response_model=CaseContactsListResponse)
def list_case_contacts(status: str = "open") -> CaseContactsListResponse:
    return CaseContactsListResponse(items=list_case_contacts_v2(status=status))


@router.get("/opportunities", response_model=CaseOpportunitiesListResponse)
def list_case_opportunities(status: str = "open") -> CaseOpportunitiesListResponse:
    return CaseOpportunitiesListResponse(items=list_case_opportunities_v2(status=status))


@router.post("/contacts/{case_id}/promote", response_model=CasePromotionResponse)
def promote_case_contact(
    case_id: str,
    payload: CasePromotionRequest,
    db: Session = Depends(get_db),
) -> CasePromotionResponse:
    promoted = promote_case_contact_v2(
        case_id,
        promotion_reason=payload.promotion_reason,
        gate_results=payload.gate_results,
    )
    if promoted is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case contact not found")

    promoted_id = str(promoted.get("promoted_id") or "")
    provisional_contact_id = str(promoted.get("provisional_contact_id") or "")
    if promoted_id:
        email = str(promoted.get("email") or "").strip().lower()
        display_name = promoted.get("display_name")

        existing_by_id = db.scalar(select(ContactCache).where(ContactCache.contact_id == promoted_id))
        existing_by_email = db.scalar(select(ContactCache).where(ContactCache.primary_email == email)) if email else None

        if existing_by_id is not None and existing_by_email is not None and existing_by_email.contact_id != promoted_id:
            # Prefer the promoted id and drop the duplicate email holder.
            db.delete(existing_by_email)
            existing_by_email = None

        target = existing_by_id or existing_by_email
        if target is None:
            target = ContactCache(
                contact_id=promoted_id,
                primary_email=email or f"{promoted_id}@autogenerated.local",
                display_name=display_name,
                owner_user_id=None,
                use_sensitive_in_drafts=False,
            )
            db.add(target)
        else:
            if target.contact_id != promoted_id:
                target.contact_id = promoted_id
            if email:
                target.primary_email = email
            if isinstance(display_name, str) and display_name.strip():
                target.display_name = display_name.strip()

        if provisional_contact_id and provisional_contact_id != promoted_id:
            interactions = db.scalars(select(Interaction)).all()
            for interaction in interactions:
                ids = interaction.contact_ids_json if isinstance(interaction.contact_ids_json, list) else []
                if provisional_contact_id not in ids:
                    continue
                rewritten = [promoted_id if cid == provisional_contact_id else cid for cid in ids if isinstance(cid, str)]
                interaction.contact_ids_json = sorted(set(rewritten))

        db.commit()

    return CasePromotionResponse(
        case_id=case_id,
        status=str(promoted.get("status") or "promoted"),
        entity_status=str(promoted.get("entity_status") or "canonical"),
        promoted_id=promoted_id or None,
    )


@router.post("/opportunities/{case_id}/promote", response_model=CasePromotionResponse)
def promote_case_opportunity(case_id: str, payload: CasePromotionRequest) -> CasePromotionResponse:
    promoted = promote_case_opportunity_v2(
        case_id,
        promotion_reason=payload.promotion_reason,
        gate_results=payload.gate_results,
    )
    if promoted is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Case opportunity not found")

    return CasePromotionResponse(
        case_id=case_id,
        status=str(promoted.get("status") or "promoted"),
        entity_status=str(promoted.get("entity_status") or "canonical"),
        promoted_id=str(promoted.get("promoted_id") or "") or None,
    )
